version: "2.8.6 " # Specify Docker Compose version

services:
  app_db:
    depends_on:
      - db
    image: wordpress:beta-php8.3-fpm-alpine
    volumes:
      - .:/var/www/html/wp-content/plugins/wp-gatsby
      - ./.log/app:/var/log/apache2
    environment:
      WP_URL: http://localhost:8091
      WP_DOMAIN: localhost:8091
      WORDPRESS_DB_HOST: ${DB_HOST}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: wordpress
      ADMIN_EMAIL: admin@example.com
      ADMIN_USERNAME: admin
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      ADMIN_PASSWORD: password
      WORDPRESS_DEBUG: ""
      INCLUDE_WPGRAPHIQL: "1"
      IMPORT_WC_PRODUCTS: "1"
      STRIPE_GATEWAY: "1"
    ports:
      - "8091:80"
    networks:
      - local

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - db:/var/lib/mysql
    networks:
      - local

  testing:
    depends_on:
      - app_db
    image: wpgatsby-testing:local
    volumes:
      - .:/var/www/html/wp-content/plugins/wp-gatsby
      - ./.log/testing:/var/log/apache2
      - ./codeception.dist.yml:/var/www/html/wp-content/plugins/wp-gatsby/codeception.yml
    env_file:
      - .env.dist
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_port=9000 remote_enable=1"
      DB_HOST: db
      WP_URL: http://localhost
      WP_DOMAIN: localhost
      STRIPE_GATEWAY: "1"
    networks:
      - testing

networks:
  local:
  testing:

volumes:
  db:
